package com.huijiasoft.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("admin", "id", Admin.class);
		arp.addMapping("area", "area_id", Area.class);
		arp.addMapping("country_user", "country_id", CountryUser.class);
		arp.addMapping("declare_type", "dec_id", DeclareType.class);
		arp.addMapping("degree", "degree_id", Degree.class);
		arp.addMapping("edu", "edu_id", Edu.class);
		arp.addMapping("mz", "mz_id", Mz.class);
		arp.addMapping("system", "id", System.class);
		arp.addMapping("uploads", "upload_id", Uploads.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("zzmm", "zzmm_id", Zzmm.class);
	}
}

