package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseArea;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Area extends BaseArea<Area> {
	public static final Area dao = new Area();
	
	public Page<Area> paginate(int pageNumber,int pageSize){
		return paginate(pageNumber,pageSize,"select *","from area order by area_id desc");
	}
	
}
