package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseCountryAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CountryAdmin extends BaseCountryAdmin<CountryAdmin> {
	public static final CountryAdmin dao = new CountryAdmin();
}
