package com.huijiasoft.model;

import java.util.List;

import com.huijiasoft.model.base.BaseCountryAdmin;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CountryAdmin extends BaseCountryAdmin<CountryAdmin> {
	public static final CountryAdmin dao = new CountryAdmin();
	
	//获取所有县区管理员
	public List<CountryAdmin> getAllCountryAdmin(){
		return dao.find("select * from country_admin order by id desc");
	}
}
