package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseCountryUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CountryUser extends BaseCountryUser<CountryUser> {
	public static final CountryUser dao = new CountryUser();
}
