package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseDec;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dec extends BaseDec<Dec> {
	public static final Dec decModel = new Dec();
	
	public Page<Dec> paginate(int pageNumber,int pageSize){
		return paginate(pageNumber, pageSize, "select *", "from dec order by dec_id asc");
		
	}
	
}
