package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseDec;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Dec extends BaseDec<Dec> {
	public static final Dec dao = new Dec();
}
