package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseDeclareType;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DeclareType extends BaseDeclareType<DeclareType> {
	public static final DeclareType dao = new DeclareType();
	
	public Page<DeclareType> paginate(int pageNumber,int pageSize){
		return paginate(pageNumber, pageSize, "select *", "from declare_type order by dec_id asc");
		
	}
	
}
