package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseDegree;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Degree extends BaseDegree<Degree> {
	public static final Degree dao = new Degree();
}
