package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseEdu;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Edu extends BaseEdu<Edu> {
	public static final Edu dao = new Edu();
}
