package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Msg extends BaseMsg<Msg> {
	public static final Msg dao = new Msg();
}
