package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseMz;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mz extends BaseMz<Mz> {
	public static final Mz dao = new Mz();
}
