package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseMz;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Mz extends BaseMz<Mz> {
	public static final Mz dao = new Mz();
	
	public Page<Mz> paginate(int pageNumber,int pageSize){
		return paginate(pageNumber,pageSize,"select *","from mz order by mz_id asc");
	}
	
}
