package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseSystem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class System extends BaseSystem<System> {
	public static final System dao = new System();
}
