package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseUploads;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Uploads extends BaseUploads<Uploads> {
	public static final Uploads dao = new Uploads();
}
