package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseUploadPhoto;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadPhoto extends BaseUploadPhoto<UploadPhoto> {
	public static final UploadPhoto dao = new UploadPhoto();
}
