package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseUploadAudio;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadAudio extends BaseUploadAudio<UploadAudio> {
	public static final UploadAudio dao = new UploadAudio();
}
