package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseUploadVideo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadVideo extends BaseUploadVideo<UploadVideo> {
	public static final UploadVideo dao = new UploadVideo();
}
