package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseZzmm;
import com.jfinal.plugin.activerecord.Page;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zzmm extends BaseZzmm<Zzmm> {
	public static final Zzmm dao = new Zzmm();
	
	public Page<Zzmm> paginate(int pageNumber,int pageSize){
		return paginate(pageNumber,pageSize,"select *","from zzmm order by zzmm_id desc");		
	}
	
}
