package com.huijiasoft.model;

import com.huijiasoft.model.base.BaseZzmm;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Zzmm extends BaseZzmm<Zzmm> {
	public static final Zzmm dao = new Zzmm();
}
