package com.huijiasoft.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMz<M extends BaseMz<M>> extends Model<M> implements IBean {

	public void setMzId(java.lang.Integer mzId) {
		set("mz_id", mzId);
	}

	public java.lang.Integer getMzId() {
		return get("mz_id");
	}

	public void setMzname(java.lang.String mzname) {
		set("mzname", mzname);
	}

	public java.lang.String getMzname() {
		return get("mzname");
	}

}
