package com.huijiasoft.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDegree<M extends BaseDegree<M>> extends Model<M> implements IBean {

	public void setDegreeId(java.lang.Integer degreeId) {
		set("degree_id", degreeId);
	}

	public java.lang.Integer getDegreeId() {
		return get("degree_id");
	}

	public void setDegreename(java.lang.String degreename) {
		set("degreename", degreename);
	}

	public java.lang.String getDegreename() {
		return get("degreename");
	}

}
