package com.huijiasoft.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseArea<M extends BaseArea<M>> extends Model<M> implements IBean {

	public void setAreaId(java.lang.Integer areaId) {
		set("area_id", areaId);
	}

	public java.lang.Integer getAreaId() {
		return get("area_id");
	}

	public void setAdd1(java.lang.String add1) {
		set("add_1", add1);
	}

	public java.lang.String getAdd1() {
		return get("add_1");
	}

	public void setJibie(java.lang.String jibie) {
		set("jibie", jibie);
	}

	public java.lang.String getJibie() {
		return get("jibie");
	}

}
