package com.huijiasoft.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseConfig<M extends BaseConfig<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUploadSize(java.lang.Integer uploadSize) {
		set("upload_size", uploadSize);
	}

	public java.lang.Integer getUploadSize() {
		return get("upload_size");
	}

	public void setExamineMonth(java.lang.Integer examineMonth) {
		set("examine_month", examineMonth);
	}

	public java.lang.Integer getExamineMonth() {
		return get("examine_month");
	}

	public void setExamineTimes(java.lang.Integer examineTimes) {
		set("examine_times", examineTimes);
	}

	public java.lang.Integer getExamineTimes() {
		return get("examine_times");
	}

}
