package com.huijiasoft.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseEdu<M extends BaseEdu<M>> extends Model<M> implements IBean {

	public void setEduId(java.lang.Integer eduId) {
		set("edu_id", eduId);
	}

	public java.lang.Integer getEduId() {
		return get("edu_id");
	}

	public void setEduname(java.lang.String eduname) {
		set("eduname", eduname);
	}

	public java.lang.String getEduname() {
		return get("eduname");
	}

}
