package com.huijiasoft.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setAge(java.lang.Integer age) {
		set("age", age);
	}

	public java.lang.Integer getAge() {
		return get("age");
	}

	public void setArtType(java.lang.Integer artType) {
		set("art_type", artType);
	}

	public java.lang.Integer getArtType() {
		return get("art_type");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setDecId(java.lang.Integer decId) {
		set("dec_id", decId);
	}

	public java.lang.Integer getDecId() {
		return get("dec_id");
	}

	public void setSbdate(java.lang.String sbdate) {
		set("sbdate", sbdate);
	}

	public java.lang.String getSbdate() {
		return get("sbdate");
	}

	public void setUsersex(java.lang.Integer usersex) {
		set("usersex", usersex);
	}

	public java.lang.Integer getUsersex() {
		return get("usersex");
	}

	public void setMzId(java.lang.Integer mzId) {
		set("mz_id", mzId);
	}

	public java.lang.Integer getMzId() {
		return get("mz_id");
	}

	public void setZzmmId(java.lang.Integer zzmmId) {
		set("zzmm_id", zzmmId);
	}

	public java.lang.Integer getZzmmId() {
		return get("zzmm_id");
	}

	public void setDegreeId(java.lang.Integer degreeId) {
		set("degree_id", degreeId);
	}

	public java.lang.Integer getDegreeId() {
		return get("degree_id");
	}

	public void setEduId(java.lang.Integer eduId) {
		set("edu_id", eduId);
	}

	public java.lang.Integer getEduId() {
		return get("edu_id");
	}

	public void setGzdate(java.lang.String gzdate) {
		set("gzdate", gzdate);
	}

	public java.lang.String getGzdate() {
		return get("gzdate");
	}

	public void setPerson(java.lang.String person) {
		set("person", person);
	}

	public java.lang.String getPerson() {
		return get("person");
	}

	public void setCard(java.lang.String card) {
		set("card", card);
	}

	public java.lang.String getCard() {
		return get("card");
	}

	public void setAreaId(java.lang.String areaId) {
		set("area_id", areaId);
	}

	public java.lang.String getAreaId() {
		return get("area_id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}

	public java.lang.String getAddress() {
		return get("address");
	}

	public void setCompany(java.lang.String Company) {
		set("Company", Company);
	}

	public java.lang.String getCompany() {
		return get("Company");
	}

	public void setTc(java.lang.String tc) {
		set("tc", tc);
	}

	public java.lang.String getTc() {
		return get("tc");
	}

	public void setZywork(java.lang.String zywork) {
		set("zywork", zywork);
	}

	public java.lang.String getZywork() {
		return get("zywork");
	}

	public void setYsjj(java.lang.String ysjj) {
		set("ysjj", ysjj);
	}

	public java.lang.String getYsjj() {
		return get("ysjj");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}

	public java.lang.Integer getStatus() {
		return get("status");
	}

}
