package com.huijiasoft.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAdmin<M extends BaseAdmin<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setAdminname(java.lang.String adminname) {
		set("adminname", adminname);
	}

	public java.lang.String getAdminname() {
		return get("adminname");
	}

	public void setAdminpassword(java.lang.String adminpassword) {
		set("adminpassword", adminpassword);
	}

	public java.lang.String getAdminpassword() {
		return get("adminpassword");
	}

}
